DWAPlannerROS:
  acc_lim_x: 1.0

  acc_lim_y: 0.0

  acc_lim_th: 2.0

  min_vel_y: 0.0
  max_vel_y: 0.0
  max_rot_vel: 1.0
  min_rot_vel: 0.4

  yaw_goal_tolerance: 0.1

  xy_goal_tolerance: 0.3

  latch_xy_goal_tolerance: true
  sim_time: 1.7

  path_distance_bias: 5.0 
  goal_distance_bias: 9.0 
  occdist_scale: 0.01 


  oscillation_reset_dist: 0.05


  prune_plan: true

  holonomic_robot: false
